#!/bin/bash
# Arch Linux Fast Install - Быстрая установка Arch Linux https://github.com/ordanax/arch2018
# Цель скрипта - быстрое развертывание системы с вашими персональными настройками (конфиг XFCE, темы, программы и т.д.).

# В разработке принимали участие:
# Алексей Бойко https://vk.com/ordanax
# Степан Скрябин https://vk.com/zurg3
# Михаил Сарвилин https://vk.com/michael170707
# Данил Антошкин https://vk.com/danil.antoshkin
# Юрий Порунцов https://vk.com/poruncov

loadkeys ru
setfont cyr-sun16
echo 'Скрипт сделан на основе чеклиста Бойко Алексея по Установке ArchLinux'
echo 'Ссылка на чек лист есть в группе vk.com/arch4u'

echo '2.3 Синхронизация системных часов'
timedatectl set-ntp true

echo '2.4 создание разделов'

echo 'Ваша разметка диска'
lsblk

read -p "Выбор диска: " devsection
cfdisk /dev/$devsection

read -p "У Вас уже есть установленный Linux? [Y/n] " new_system
 if [[ -z $new_system || $new_system == y || $new_system == Y ]]
  then read -p "Выбор системного раздела: " rootsection
  echo '2.4.2 Форматирование диска'
  read -p "Введите имя метки тома :" mark
  mkfs.btrfs -f -L $mark /dev/$rootsection
  echo '2.4.3 Монтирование диска'
  mount /dev/$rootsection /mnt
  echo '2.4.4 Создание подтомов'
  btrfs subvolume create /mnt/@
  btrfs subvolume create /mnt/@home
  btrfs subvolume list /mnt
  umount /mnt
  mount -o subvol=@,compress=lzo,relatime,space_cache,autodefrag /dev/$rootsection /mnt
  mkdir /mnt/home
  mount -o subvol=@home,compress=lzo,relatime,space_cache,autodefrag /dev/$rootsection /mnt/home
elif [[ $new_system == n || $new_system == N ]]
  then read -p "Выбор swap раздела: " swapsection
  mkswap /dev/$swapsection -L swap
  swapon /dev/$swapsection
  read -p "Выбор системного раздела: " rootsection
  echo '2.4.2 Форматирование диска'
  read -p "Введите имя метки тома :" mark
  mkfs.btrfs -f -L $mark /dev/$rootsection
  echo '2.4.3 Монтирование диска'
  mount /dev/$rootsection /mnt
  echo '2.4.4 Создание подтомов'
  btrfs subvolume create /mnt/@
  btrfs subvolume create /mnt/@home
  btrfs subvolume list /mnt
  umount /mnt
  mount -o subvol=@,compress=lzo,relatime,space_cache,autodefrag /dev/$rootsection /mnt
  mkdir /mnt/home
  mount -o subvol=@home,compress=lzo,relatime,space_cache,autodefrag /dev/$rootsection /mnt/home
 fi

echo '3.1 Выбор зеркал для загрузки. Ставим зеркало от Яндекс'
echo "Server = http://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
echo "Server = https://mirror.yandex.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
echo "Server = http://mirror.rol.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
echo "Server = https://mirror.rol.ru/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist

echo '3.2 Установка основных пакетов'
pacstrap /mnt base base-devel

echo '3.3 Настройка системы'
genfstab -pU /mnt >> /mnt/etc/fstab

arch-chroot /mnt sh -c "$(curl -fsSL git.io/inst2)"
