#!/bin/bash
echo 'Создаем нужные директории'
sudo pacman -S xdg-user-dirs --noconfirm
xdg-user-dirs-update

echo 'Установка программ'
sudo pacman -S curl gparted gpart gnome-disk-utility ffmpeg gthumb git yajl ufw f2fs-tools dosfstools mtools ntfs-3g alsa-lib alsa-utils p7zip unrar gvfs aspell-ru pulseaudio pavucontrol --noconfirm
sudo pacman -Ry firefox --noconfirm

echo 'Установка yaourt'
cd /tmp
git clone https://aur.archlinux.org/package-query.git
cd package-query/
makepkg -si
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt/
makepkg -si
cd ..
sudo rm -dR yaourt/ package-query/
cd /home/$USER

read -p 'Установить pamac? [Y/n] ' pamac_set
if [[ -z $pamac_set || $pamac_set == y || $pamac_set == Y ]]
  then yaourt pamac-aur --noconfirm
elif [[ $pamac_set == n || $pamac_set == N ]]
  then echo 'Установка pamac пропущена.'
fi

read -p 'Установить timeshift? [Y/n] ' timeshift_set
if [[ -z $timeshift_set || $timeshift_set == y || $timeshift_set == Y ]]
  then yaourt timeshift --noconfirm
  sudo pacman -Sy cron --noconfirm
elif [[ $timeshift_set == n || $timeshift_set == N ]]
  then echo 'Установка timeshift пропущена.'
fi

read -p 'Установить steam? [Y/n] ' steam_set
if [[ -z $steam_set || $steam_set == y || $steam_set == Y ]]
  then sudo pacman -S steam --noconfirm
elif [[ $steam_set == n || $steam_set == N ]]
  then echo 'Установка timeshift пропущена.'
fi

read -p 'Установить рекомендумые программы? [Y/n] ' prog_set
if [[ -z $prog_set || $prog_set == y || $prog_set == Y ]]
  then sudo pacman -S vlc audacious gimp inkscape hwinfo libzip pstoedit mariadb-libs unixodbc --noconfirm
  yaourt -S imagewriter --noconfirm
  yaourt -S stacer --noconfirm
elif [[ $prog_set == n || $prog_set == N ]]
  then echo 'Установка программ пропущена.'
fi

read -p 'Установить Google-Chrome или Chromium? [G/c] ' chrome_set
if [[ -z $chrome_set || $chrome_set == g || $chrome_set == G ]]
  then  yaourt -S google-chrome --noconfirm
elif [[ $chrome_set == c || $chrome_set == C ]]
  then sudo pacman -S chromium --noconfirm
  else echo "Как хотите. "
fi

read -p 'Установить Libre Office ? [Y/n] ' of_set
if [[ -z $of_set || $of_set == y || $of_set == Y ]]
  then sudo pacman -S libreoffice libreoffice-fresh-ru --noconfirm
elif [[ $of_set == n || $of_set == N ]]
  then echo 'Установка пропущена.'
fi

sudo pacman -S zsh
chsh -s /bin/zsh
curl -L http://install.ohmyz.sh | sh

echo 'Включаем сетевой экран'
sudo ufw enable

echo 'Добавляем в автозагрузку:'
sudo systemctl enable ufw

read -p 'У вас проприетарный драйвер nVidia? [Y/n] ' nv_set
if [[ -z $nv_set || $nv_set == y || $nv_set == Y ]]
  then wget https://raw.githubusercontent.com/zahar77735/arch-inst-scr/master/files/NVIDIACONFIG.desktop
  chmod 644 NVIDIACONFIG.desktop
  mkdir /home/$USER/.config/autostart/
  mv NVIDIACONFIG.desktop ~/.config/autostart/nvidia-config.desktop
  sudo nvidia-xconfig --cool-bits=12
elif [[ $nv_set == N || $nv_set == n ]]
  then echo 'Ну нет так нет.'
fi

read -p 'Вы установили KDE? [Y/n] ' kde_set
if [[ -z $kde_set || $kde_set == Y || $kde_set == y ]]
  then touch /home/$USER/.face
  ln -s /home/$USER/.face /home/$USER/.face.icon
  setfacl -m u:sddm:x /home/$USER/
  setfacl -m u:sddm:r /home/$USER/.face.icon
elif [[ $kde_set == n || $kde_set == N ]]
  then echo 'Ну нет так нет.'
fi

sudo grub-mkconfig -o /boot/grub/grub.cfg

echo 'Установка завершена!'


