#!/bin/bash
clear
loadkeys ru
setfont cyr-sun16
#echo 'Скрипт сделан на основе чеклиста Бойко Алексея по Установке ArchLinux'
#echo 'Ссылка на чек лист есть в группе vk.com/arch4u'

echo 'Синхронизация системных часов'
timedatectl set-ntp true

echo 'Создание разделов'

echo 'Ваша разметка диска'
lsblk

read -p 'Выбрать диск? ' xhdd
fdisk /dev/$xhdd
read -p "Выберите раздел куда будет установлена система: " rootsection
read -p "Введите имя метки тома: " mark
read -p "Выберите раздел для boot: " efi
mkfs.ext4 -L $mark /dev/$rootsection
mkfs.fat -F32 /dev/$efi
mount /dev/$rootsection /mnt
#btrfs subvolume create /mnt/@
#btrfs subvolume create /mnt/@home
#umount /mnt -R
#mount -o subvol=/@,rw,noatime,autodefrag,compress=zstd:3,discard=async,ssd,ssd_spread,space_cache=v2 /dev/$rootsection /mnt
mkdir /mnt/boot
mkdir /mnt/boot/efi
#mkdir /mnt/home
#mount -o subvol=/@home,rw,noatime,autodefrag,compress=zstd:3,discard=async,ssd,ssd_spread,space_cache=v2 /dev/$rootsection /mnt/home
mount -t vfat /dev/$efi /mnt/boot/efi

#echo 'Выбор зеркал для загрузки.'
#nano /etc/pacman.d/mirrorlist
pacman -Sy

echo 'Установка основных пакетов'
pacstrap /mnt base base-devel linux-zen linux-firmware linux-zen-headers amd-ucode nano

genfstab -pU /mnt >> /mnt/etc/fstab

arch-chroot /mnt sh -c "$(curl -fsSL git.io/inst2)"
