#!/bin/bash
echo 'Создаем нужные директории'
sudo pacman -S xdg-user-dirs --noconfirm
xdg-user-dirs-update

echo 'Установка программ'
sudo pacman -S curl gparted gpart gnome-disk-utility ffmpeg gthumb git yajl ufw f2fs-tools dosfstools mtools ntfs-3g alsa-lib alsa-utils p7zip unrar gvfs aspell-ru pulseaudio pavucontrol --noconfirm
sudo pacman -Ry firefox --noconfirm

echo 'Установка yaourt'
cd /tmp
git clone https://aur.archlinux.org/package-query.git
cd package-query/
makepkg -si
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt/
makepkg -si
cd ..
sudo rm -dR yaourt/ package-query/
cd /home/$USER

echo 'Установить pamac?'
read -p "1 - Да, 0 - Нет: " pamac_set
if [[ $pamac_set == 1 ]]; then
  yaourt pamac-aur --noconfirm
elif [[ $pamac_set == 0 ]]; then
  echo 'Установка pamac пропущена.'
fi

echo 'Установить timeshift?'
read -p "1 - Да, 0 - Нет: " timeshift_set
if [[ $timeshift_set == 1 ]]; then
  yaourt timeshift --noconfirm
  sudo pacman -Sy cron --noconfirm
elif [[ $timeshift_set == 0 ]]; then
  echo 'Установка timeshift пропущена.'
fi

echo 'Установить steam?'
read -p "1 - Да, 0 - Нет: " steam_set
if [[ $steam_set == 1 ]]; then
  sudo pacman -S steam --noconfirm
elif [[ $steam_set == 0 ]]; then
  echo 'Установка timeshift пропущена.'
fi

echo 'Установить рекомендумые программы?'
read -p "1 - Да, 0 - Нет: " prog_set
if [[ $prog_set == 1 ]]; then
  sudo pacman -S vlc audacious gimp libreoffice libreoffice-fresh-ru inkscape hwinfo libzip pstoedit mariadb-libs unixodbc libva-vdpau-driver --noconfirm
  yaourt -S google-chrome --noconfirm 
  yaourt -S imagewriter --noconfirm
elif [[ $prog_set == 0 ]]; then
  echo 'Установка программ пропущена.'
fi

sudo pacman -S zsh
chsh -s /bin/zsh
curl -L http://install.ohmyz.sh | sh

echo 'alias update-grub="grub-mkconfig -o /boot/grub/grub.cfg"' >> ~/.zshrc
echo 'Включаем сетевой экран'
sudo ufw enable

echo 'Добавляем в автозагрузку:'
sudo systemctl enable ufw

echo 'У вас nVidia?'
read -p "1 - Да, 0 - Нет: " nv_set
if [[ $nv_set == 1 ]]; then
  wget https://raw.githubusercontent.com/zahar77735/arch-inst-scr/master/files/NVIDIACONFIG.desktop
  chmod 644 NVIDIACONFIG.desktop
  mkdir /home/$USER/.config/autostart/
  mv NVIDIACONFIG.desktop ~/.config/autostart/NVIDIACONFIG.desktop
  sudo nvidia-xconfig --cool-bits=12
elif [[ $nv_set == 0 ]]; then
  echo 'Ну нет так нет.'
fi

echo 'Вы установили KDE?'
read -p "1 - Да, 0 - Нет: " kde_set
if [[ $kde_set == 1 ]]; then
  touch /home/$USER/.face
  ln -s /home/$USER/.face /home/$USER/.face.icon
  setfacl -m u:sddm:x /home/$USER/
  setfacl -m u:sddm:r /home/$USER/.face.icon
elif [[ $kde_set == 0 ]]; then
  echo 'Ну нет так нет.'
fi

sudo grub-mkconfig -o /boot/grub/grub.cfg

echo 'Установка завершена!'


