#!/bin/bash
clear
read -p "Введите имя компьютера: " hostname
read -p "Введите имя пользователя: " username

echo 'Прописываем имя компьютера'
echo $hostname > /etc/hostname
ln -svf /usr/share/zoneinfo/Europe/Moscow /etc/localtime

echo '3.4 Добавляем русскую локаль системы'
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
echo "ru_RU.UTF-8 UTF-8" >> /etc/locale.gen 

echo 'Обновим текущую локаль системы'
locale-gen

echo 'Указываем язык системы'
echo 'LANG="ru_RU.UTF-8"' >> /etc/locale.conf
echo 'LC_MESSAGES="ru_RU.UTF-8"' >> /etc/locale.conf

echo 'Вписываем KEYMAP=ru FONT=cyr-sun16'
echo 'KEYMAP=ru' >> /etc/vconsole.conf
echo 'FONT=cyr-sun16' >> /etc/vconsole.conf

echo 'Установка доп. приложений'
pacman -S wget mc pkgfile man --noconfirm
pkgfile --update

sed -i 's/HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)/HOOKS=(base udev autodetect modconf block filesystems keyboard)/' ./etc/mkinitcpio.conf

echo 'Создадим загрузочный RAM диск'
mkinitcpio -p linux-zen

echo '3.5 Устанавливаем загрузчик'
read -p "Введите раздел куда установим загрузчик: " esp
bootctl --path=/boot install

echo 'Ставим программу для Wi-fi'
pacman -S dialog wpa_supplicant --noconfirm 

echo 'Добавляем пользователя'
useradd -m -g users -G wheel,audio,video,storage -s /bin/bash $username

echo 'Создаем root пароль'
passwd

echo 'Устанавливаем пароль пользователя'
passwd $username

echo 'Устанавливаем SUDO'
echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers

echo 'Раскомментируем репозиторий multilib Для работы 32-битных приложений в 64-битной системе.'
echo '[multilib]' >> /etc/pacman.conf
echo 'Include = /etc/pacman.d/mirrorlist' >> /etc/pacman.conf
pacman-key --init
pacman-key --populate archlinux
pacman -Syy

read -p "Установить иксы? [Y/n]" vm_set
if [[ -z $vm_set || $vm_set == y || $vm_set == Y ]]
  then pacman -S xorg-server xorg-drivers xorg-xinit --noconfirm
elif [[ $vm_set == n || $vm_set == N ]]
  then echo 'Пропущена установка'
fi

echo ""
echo ""
echo "Какое окружение будем ставить? Скрипт может установить XFCE, KDE или GNOME "
echo "для этого укажите [G/X/K], Можно пропустить установку нажав Enter "
read -p "Можно ввести произвольную команду либо команды разделяя их && "$'\n' vm_setting
if [[ -z $vm_setting ]]
  then echo "Пропускаем установку GUI"
  sleep 5
elif [[ $vm_setting == x || $vm_setting == X ]]
  then pacman -S xfce4 xfce4-goodies file-roller gthumb plank gnome-calculator gedit dconf-editor pantheon-polkit-agent evince alsa-plugins pulseaudio-alsa libmtp mtpfs gvfs-mtp gvfs-gphoto2 --noconfirm
  pacman -Rscu mousepad --noconfirm
  pacman -S lightdm-gtk-greeter --noconfirm
  systemctl enable lightdm
  sleep 5
elif [[ $vm_setting == k || $vm_setting == K ]]
  then pacman -Sy plasma konsole kate dolphin sddm packagekit-qt5 qt5-xmlpatterns spectacle okular ark gwenview --noconfirm
  sleep 5
  systemctl enable sddm
  sleep 5
elif [[ $vm_setting == g || $vm_setting == G ]] 
  then pacman -S gnome gnome-shell gdm gnome-tweaks gthumb --noconfirm
  sleep 5
  systemctl enable gdm
  sleep 5
else $vm_setting
fi

echo "изменяем активный планировщик ввода-вывода"
wget https://raw.githubusercontent.com/zahar77735/arch-inst-scr/master/files/60-ioschedulers.rules
mv 60-ioschedulers.rules /etc/udev/rules.d/60-ioschedulers.rules
chmod 644 /etc/udev/rules.d/60-ioschedulers.rules
sleep 5

echo 'Ставим шрифты'
pacman -S ttf-liberation ttf-dejavu ttf-ubuntu-font-family --noconfirm 

echo 'Ставим сеть'
pacman -S networkmanager network-manager-applet ppp --noconfirm

echo 'Подключаем автозагрузку менеджера входа и интернет'
systemctl enable NetworkManager

echo 'Установка завершена! Перезагрузите систему.'

exit

